# -*- coding: utf-8 -*-
"""Untitled.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mg4vOzmRiPC3-7-hdepNN8eKBAaLjgtH
"""

import numpy as np
from sklearn import linear_model
import sklearn.metrics as sm

input_file = '/content/drive/My Drive/Colab Notebooks/Artificial-Intelligence-with-Python/Chapter2/data_multivar_regr.txt'

data = np.loadtxt(input_file,delimiter = ',')
X, y = data[:,:-1], data[:, -1]

